### ISSUE TITLE
Agricraft - Incomplete/bugs

### ISSUE THREAD

**Issue by itsyaboicold** [PSILONCRAFT/psiloncrafted#11]
you cant put some seeds on cropsticks.
and as of 1.10.1 you can still grow every single seed in the game with just 2 crop sticks

**Comment by PSILONCRAFT** [comment]
Checking on it

**Comment by MeisterGeekz** [comment]
Crop stick issue has been fixed for server side. Will need to push new version for client for single player worlds. 

Missing recipes are being looked at and added if applicable

**Comment by itsyaboicold** [comment]
Mutations are fixed, Recipe's need fixing (didn't know but you're already on the case) and some seeds can not be placed onto cropsticks yet (sorry for whining)

**Comment by MeisterGeekz** [comment]
Added Certus Quartz Seeds, recipes and made plantable 
Added Osmium Seeds, recipes and made plantable
Removed Fluix Seeds from Mystical Agriculture to encourage use of AE2 methods of obtaining Fluix
Removed Glowstone Ingot from Mystical Agriculture to encourage use of Mekanism machines
