### ISSUE TITLE
Actually Additions - Spawner Changer not changing to the right type of mob

### ISSUE THREAD

**Issue by itsyaboicold** [PSILONCRAFT/psiloncrafted#12]
captured a wither skeleton gave me back a skeleton when using actually additions

**Comment by MeisterGeekz** [comment]
After research this is actually intended behavior. The ID of the Wither skeleton is just "skeleton" meaning in the overworld they will just spawn regular skeletons. So you have to use them either in the nether or build a powered spawner from EnderIO.
