### ISSUE TITLE
Investigate into title entities disappearing when placed

### ISSUE THREAD

**Issue by MeisterGeekz** [PSILONCRAFT/psiloncrafted#16]
Tile entities such as Digital miner and Applied Energistics drives  vanishing when placed in the world and player leaves the chunk they are in

**Comment by PSILONCRAFT** [comment]
In response to This i removed foamfix. Has it been any more tiles gone missing now resently?

**Comment by MeisterGeekz** [comment]
Yeah. There have been more AE drives, crafting terminal, cables and 1 miner vanishing since

**Comment by PSILONCRAFT** [comment]
Do You know Where?

**Comment by MeisterGeekz** [comment]
X506 Z289 Y64

**Comment by PSILONCRAFT** [comment]
https://github.com/aidancbrady/Mekanism/issues/3662

Seems that there is an issue with This but no logs or errormessages

**Comment by PSILONCRAFT** [comment]
Tested this issue over several days. and found that some rare chunks are acting wierd. cant find any log entry or error message about ae2 blocks. closing the issue for now

**Comment by PSILONCRAFT** [comment]
Do you play my modpack still i kinda have abandoned it

**Comment by texaswriter** [comment]
Sorry. I guess I meant that to go somewhere else, not a modback github repository.
