### ISSUE TITLE
AA Storage Crate Upgrades

### ISSUE THREAD

**Issue by Nezmin2** [PSILONCRAFT/psiloncrafted#21]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
When attempting to apply the storage upgrade to the storage crate, nothing happens

## Reproduce Steps
Craft a small storage crate from the Actually Additions mod and then a small to medium storage crate upgrade and attempt to apply.

**Comment by PSILONCRAFT** [comment]
Testes it and it works fine. 

You need to start with a plain chest and do a upgrade on it. Then You can upgrade to different tiers from there
