### ISSUE TITLE
Request - Agricraft Farming Station

### ISSUE THREAD

**Issue by itsyaboicold** [PSILONCRAFT/psiloncrafted#3]
https://github.com/HenryLoenwind/EnderIOAddons/wiki/AgriCraft-Farming-Station

**Comment by PSILONCRAFT** [comment]
I will look into it

**Comment by MeisterGeekz** [comment]
I don't think there is a 1.10 version of this available yet.

**Comment by PSILONCRAFT** [comment]
no version for 1.10.2
