### ISSUE TITLE
Villager spawns

### ISSUE THREAD

**Issue by maxmax9339** [PSILONCRAFT/psiloncrafted#5]
I came across a village and there were 1000 Villagers.

Seems like a bug to me. (It was also very laggy)

![2017-04-28_20 57 24](https://cloud.githubusercontent.com/assets/26333994/25543361/820d1086-2c56-11e7-86c0-2f3cd1583e8f.png)
![2017-04-28_20 57 28](https://cloud.githubusercontent.com/assets/26333994/25543364/840c8aec-2c56-11e7-88a4-a7b4b0f45581.png)

**Comment by PSILONCRAFT** [comment]
I will take a look at it

**Comment by PSILONCRAFT** [comment]
changed the mca.cfg

# Villagers automatically get married, have children, etc.
    B:"Story progression"=false
