### ISSUE TITLE
Gendustry tooltips are broken.

### ISSUE THREAD

**Issue by DesmondTaylor** [PSILONCRAFT/psiloncrafted#6]
**Gendustry** tooltips are broken.

If you look at the items in JEI it has the tooltip of: **"Tooltip error, see log"**

Image link included:
http://imgur.com/N0yn4Hw

**Comment by MeisterGeekz** [comment]
Gendutry is missing from server mods but present in client. Will add to server.

**Comment by PSILONCRAFT** [comment]
mod uploaded to server. takes effect after nest reboot
