### ISSUE TITLE
WAILA is not showing Chicken information whilst in a Hatchery nest.

### ISSUE THREAD

**Issue by DesmondTaylor** [PSILONCRAFT/psiloncrafted#7]
If you look at the fool craft pack you'll see that when looking at a chicken in a nesting pen the information on what is in the pen and also the timer of when the chicken will next drop.

I believe it could just be a config option that needs changing.

Image included below:
http://imgur.com/rnMoSfw

**Comment by PSILONCRAFT** [comment]
Gonna take a look at it

**Comment by PSILONCRAFT** [comment]
this feature will be fixed in the 1.0.7 release

**Comment by PSILONCRAFT** [comment]
Waila got replaced by hwawla fixed the issue with nesting statusview
