### ISSUE TITLE
Mystical Agriculture

### ISSUE THREAD

**Issue by Ishrawrz** [PSILONCRAFT/psiloncrafted#8]
No recipe for tier one mob chunks, was previously obtained via lootbags

**Comment by PSILONCRAFT** [comment]
Use ingame crafted Stord from the mod to get the mobchunks

**Comment by PSILONCRAFT** [comment]
Might add to loot table in 1.0.9

**Comment by itsyaboicold** [comment]
Mob seeds require chunks of their respective mob. To obtain these you must kill the monsters with a Soulium Dagger. The drop chance is shown in the tooltip of the chunk.

You can also craft them using 'blank' Mob Chunks. These are created by smelting any mob chunk in a furnace. 

Pulled from the wiki, checked the server and the recipe is there.
